#!/usr/bin/env python3
"""Shorts Studio command line.

  python main.py init                      create the workspace folders + database
  python main.py make-fixtures             generate self-made CC0 test footage + example research notes
  python main.py research --topic "..."    research a topic (or --trends / --niche-report)
  python main.py discover-sources --topic "..."
  python main.py verify-sources [--list | --approve ID | --reject ID]
  python main.py generate-script --topic "..."
  python main.py generate-video --video ID  narration, captions, storyboard, render (+ QC)
  python main.py qc --video ID
  python main.py review [--video ID] [--approve|--reject|--render-again|--schedule WHEN ...]
  python main.py upload --video ID [--privacy unlisted] [--live]
  python main.py analytics [--collect | --import-csv FILE | --record ID --views N ...]
  python main.py experiments {create,list,assign,analyze}
  python main.py dashboard | costs | finance | calendar | status
  python main.py pipeline --topic "..."     research -> sources -> script -> video -> QC -> review
  python main.py pipeline --auto-research   pick the next topic from trend/idea providers
"""
from __future__ import annotations

import argparse
import getpass
import json
import os
import sys
from pathlib import Path


def _ctx(args):
    from studio.context import StudioContext
    return StudioContext.create(args.home)


def _reviewer(args) -> str:
    return getattr(args, "reviewer", None) or os.environ.get("STUDIO_REVIEWER") or getpass.getuser()


def _print(obj) -> None:
    print(obj if isinstance(obj, str) else json.dumps(obj, indent=2, default=str, ensure_ascii=False))


def _topic_id(ctx, topic: str) -> str:
    from studio.research.topic_research import get_or_create_topic
    return get_or_create_topic(ctx, topic)["topic_id"]


# -- commands -----------------------------------------------------------------------------
def cmd_init(args):
    ctx = _ctx(args)
    _print({"workspace": str(ctx.ws.home), "database": str(ctx.ws.db_path), "dry_run": ctx.cfg.dry_run,
            "auto_publish": ctx.cfg.auto_publish, "manual_approval": ctx.cfg.manual_approval})


def cmd_make_fixtures(args):
    from studio.sources.fixtures import build_fixture_library
    ctx = _ctx(args)
    made = build_fixture_library(ctx.ws.home / "sources" / "library", ctx.cfg.path(ctx.cfg.get("research.notes_dir")))
    _print({"footage": [str(m) for m in made], "notes": str(ctx.cfg.path(ctx.cfg.get("research.notes_dir"))),
            "license": "CC0 (self-generated by this project)"})


def cmd_research(args):
    ctx = _ctx(args)
    if args.niche_report:
        from studio.research.niche import build_report
        rep = build_report(ctx, niches=args.niches.split(",") if args.niches else None)
        print(Path(rep["markdown_path"]).read_text())
        return
    if args.trends:
        from studio.research.trends import discover_trends
        out = discover_trends(ctx)
        _print({"topics": [{k: t[k] for k in ("topic_id", "topic", "category", "trend_signal", "timeliness",
                                               "evergreen_score", "research_status", "date_detected")}
                           for t in out["topics"]], "provider_errors": out["provider_errors"]})
        return
    if not args.topic:
        raise SystemExit("research needs --topic, --trends or --niche-report")
    from studio.research.topic_research import research_topic
    _print(research_topic(ctx, _topic_id(ctx, args.topic)))


def cmd_discover_sources(args):
    from studio.pipeline.orchestrator import source_queries
    from studio.sources.discovery import discover
    ctx = _ctx(args)
    tid = _topic_id(ctx, args.topic)
    queries = [args.query] if args.query else source_queries(ctx, tid)
    rep = discover(ctx, queries=queries, topic_id=tid)
    _print({"queries": queries, "approved": rep.approved,
            "rejected": [{"source_id": s, "reasons": r} for s, r in rep.rejected],
            "provider_errors": rep.provider_errors})


def cmd_verify_sources(args):
    from studio.sources.discovery import human_verify
    ctx = _ctx(args)
    if args.approve or args.reject:
        human_verify(ctx, args.approve or args.reject, reviewer=_reviewer(args), approve=bool(args.approve),
                     license_type=args.license, permission_reference=args.reference, permission_date=args.date,
                     notes=args.notes)
    rows = ctx.db.query("SELECT source_id, status, license_type, rights_confidence, verification_status, title, "
                        "creator, source_url FROM source_rights ORDER BY date_found")
    for r in rows:
        print(f"{r['source_id']}  {r['status']:<9} {str(r['license_type']):<14} conf={r['rights_confidence']}  "
              f"{r['title']} — {r['creator']}")
    rejected = ctx.db.select("sources", {"status": "REJECTED"})
    if rejected and not (args.approve or args.reject):
        print("\nRejected sources and why:")
        for s in rejected:
            print(f"  {s['source_id']}: {s['rejection_reason']}")


def cmd_generate_script(args):
    from studio.content.script import generate_script
    ctx = _ctx(args)
    s = generate_script(ctx, _topic_id(ctx, args.topic), target_duration=args.duration)
    print(f"script {s['script_id']} ({s['llm_provider']}), ~{s['est_duration']}s, fact check {s['factcheck_status']}")
    print("hooks:")
    for h in s["hooks_json"]:
        print(f"  {h['score']:>6}  {h['text']}")
    for sec in s["sections_json"]:
        print(f"[{sec['name']}]")
        for x in sec["sentences"]:
            print(f"  {x['text']}")
    print(f"saved: {s['path']}")


def cmd_generate_video(args):
    from studio.pipeline.orchestrator import run_stages
    ctx = _ctx(args)
    _print(run_stages(ctx, args.video, ["editing", "qc"]))


def cmd_qc(args):
    from studio.pipeline.orchestrator import run_stages
    ctx = _ctx(args)
    res = run_stages(ctx, args.video, ["qc"])
    for c in res["stages"]["qc"]["checks"] if "qc" in res.get("stages", {}) else []:
        print(f"{'PASS' if c['passed'] else 'FAIL'}  {c['name']}: {c['details']}")
    print(f"status: {res['status']}")


def cmd_review(args):
    from studio.review import review
    from studio.review.html import write_review_page
    ctx = _ctx(args)
    if not args.video:
        rows = review.pending(ctx)
        if not rows:
            print("Nothing waiting for review.")
        for v in rows:
            print(f"{v['video_id']}  {v.get('selected_title')}")
        return
    who = _reviewer(args)
    if args.approve:
        review.approve(ctx, args.video, who, allow_public=args.allow_public, notes=args.notes)
        print(f"APPROVED by {who}" + (" (public release allowed)" if args.allow_public else " (private/unlisted only)"))
        if ctx.cfg.auto_upload:
            from studio.publish.youtube import upload
            _print(upload(ctx, args.video, explicit=False))
    elif args.reject:
        review.reject(ctx, args.video, who, notes=args.notes)
        print("REJECTED")
    elif args.edit_title or args.edit_description_file:
        desc = Path(args.edit_description_file).read_text() if args.edit_description_file else None
        review.edit_metadata(ctx, args.video, who, title=args.edit_title, description=desc)
        print(f"edited; status now {ctx.db.get('videos', args.video)['status']}")
    elif args.edit_script:
        _print(review.edit_script(ctx, args.video, who, Path(args.edit_script).read_text()))
    elif args.render_again:
        _print(review.render_again(ctx, args.video, who, notes=args.notes))
    elif args.schedule:
        review.schedule(ctx, args.video, who, args.schedule, allow_public=args.allow_public)
        print(f"SCHEDULED for {args.schedule} (the upload command sends it as private with publishAt)")
    else:
        print(review.summary(ctx, args.video))
        print(f"\nreview page: {write_review_page(ctx, args.video)}")
        if sys.stdin.isatty() and ctx.db.get("videos", args.video)["status"] == "REVIEW":
            choice = input("\n[a]pprove  [r]eject  [g] render again  [q]uit > ").strip().lower()
            if choice == "a":
                public = input("Allow PUBLIC release? [y/N] ").strip().lower() == "y"
                review.approve(ctx, args.video, who, allow_public=public)
                print("APPROVED")
            elif choice == "r":
                review.reject(ctx, args.video, who, notes=input("Reason: "))
                print("REJECTED")
            elif choice == "g":
                _print(review.render_again(ctx, args.video, who))


def cmd_upload(args):
    from studio.publish.youtube import upload
    ctx = _ctx(args)
    res = upload(ctx, args.video, privacy=args.privacy, explicit=True, live=args.live)
    _print({k: res[k] for k in ("upload_id", "status", "privacy_status", "publish_at", "dry_run")
            if k in res} | ({"youtube_video_id": res["youtube_video_id"]} if res.get("youtube_video_id") else {}))
    if res["status"] == "DRY_RUN":
        print("DRY RUN: nothing was sent. The exact request is in exports/<video>/upload_request.json")


def cmd_analytics(args):
    from studio.analytics import collector
    ctx = _ctx(args)
    if args.collect:
        from studio.publish.youtube import mark_scheduled_published
        moved = mark_scheduled_published(ctx)
        n = collector.collect_api(ctx)
        _print({"snapshots": n, "scheduled_now_published": moved})
    elif args.import_csv:
        _print({"snapshots": collector.import_studio_csv(ctx, args.import_csv)})
    elif args.record:
        metrics = {k: getattr(args, k) for k in ("views", "likes", "comments", "shares", "subscribers_gained",
                                                  "avg_view_percentage") if getattr(args, k) is not None}
        _print({"snapshot_id": collector.snapshot(ctx, args.record, source="manual", **metrics)})
    else:
        _print(collector.latest_by_video(ctx))


def cmd_experiments(args):
    from studio.analytics import experiments as ex
    ctx = _ctx(args)
    if args.action == "create":
        _print({"experiment_id": ex.create(ctx, name=args.name, variable=args.variable,
                                           variants=args.variants.split(","), hypothesis=args.hypothesis,
                                           metric=args.metric)})
    elif args.action == "assign":
        variant = args.variant or ex.next_variant(ctx, args.experiment)
        ex.assign(ctx, args.experiment, args.video, variant)
        print(f"{args.video} -> {variant}")
    elif args.action == "analyze":
        _print(ex.analyze(ctx, args.experiment))
    else:
        _print(ex.describe(ctx))


def cmd_dashboard(args):
    from studio.analytics.dashboard import dashboard_data
    from studio.review.html import write_dashboard
    ctx = _ctx(args)
    data = dashboard_data(ctx)
    print(f"dashboard: {write_dashboard(ctx, data)}")
    _print(data["kpis"])
    for line in data["what_is_working"]:
        print(" -", line)


def cmd_costs(args):
    from studio.analytics.costs import cost_summary
    _print(cost_summary(_ctx(args)))


def cmd_finance(args):
    from studio.analytics import finance
    ctx = _ctx(args)
    if args.add_revenue is not None:
        finance.add_revenue(ctx, amount_usd=args.add_revenue, category=args.category, period_start=args.start,
                            period_end=args.end, video_id=args.video, notes=args.notes)
    _print(finance.model(ctx, hypothetical_rpm=args.hypothetical_rpm, assume_shorts_eligible=args.assume_eligible,
                         fixed_monthly_costs=args.fixed_monthly))


def cmd_calendar(args):
    from studio.pipeline.states import ALL
    ctx = _ctx(args)
    for status in ALL:
        rows = ctx.db.select("videos", {"status": status}, order_by="created_at")
        if rows:
            print(f"{status} ({len(rows)})")
            for v in rows:
                print(f"   {v['video_id']}  {v.get('selected_title') or ''}")
    from studio.pipeline.orchestrator import videos_created_today
    print(f"\ncreated today: {videos_created_today(ctx)} / {ctx.cfg.get('production.max_daily_videos')} "
          f"(posting frequency: {ctx.cfg.get('production.posting_frequency')})")


def cmd_pipeline(args):
    from studio.pipeline import orchestrator as o
    ctx = _ctx(args)
    if args.resume:
        res = o.resume(ctx, args.resume, from_stage=args.from_stage)
    elif args.auto_research:
        topic = o.auto_research_topic(ctx)
        if topic is None:
            raise SystemExit("No topic available from trend/idea providers — add ideas to config/topic_ideas.yaml")
        print(f"auto-research picked: {topic['topic']} (signal: {topic['trend_signal']}, {topic['timeliness']})")
        res = o.run_pipeline(ctx, topic_id=topic["topic_id"])
    elif args.topic:
        res = o.run_pipeline(ctx, topic=args.topic)
    else:
        raise SystemExit("pipeline needs --topic, --auto-research or --resume")
    _print(res)
    if res.get("status") == "REVIEW":
        print(f"\nReady for review. Open {res['review_page']}\nthen: python main.py review --video {res['video_id']}")


def cmd_status(args):
    ctx = _ctx(args)
    counts = ctx.db.query("SELECT status, COUNT(*) AS n FROM videos GROUP BY status")
    errors = ctx.db.query("SELECT stage, error_type, message, created_at FROM errors WHERE resolved = 0 "
                          "ORDER BY created_at DESC LIMIT 5")
    _print({"videos": {c["status"]: c["n"] for c in counts}, "recent_errors": errors, "dry_run": ctx.cfg.dry_run,
            "auto_publish": ctx.cfg.auto_publish, "manual_approval": ctx.cfg.manual_approval,
            "llm": ctx.cfg.get("content.llm_provider"), "tts": ctx.cfg.get("voice.provider")})


# -- parser ----------------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="main.py", description="Shorts Studio")
    p.add_argument("--home", help="workspace root (default: STUDIO_HOME or this directory)")
    p.add_argument("--debug", action="store_true", help="show tracebacks")
    sub = p.add_subparsers(dest="command", required=True)

    sub.add_parser("init").set_defaults(func=cmd_init)
    sub.add_parser("make-fixtures").set_defaults(func=cmd_make_fixtures)
    r = sub.add_parser("research")
    r.add_argument("--topic")
    r.add_argument("--trends", action="store_true")
    r.add_argument("--niche-report", action="store_true")
    r.add_argument("--niches", help="comma-separated subset for the niche report")
    r.set_defaults(func=cmd_research)
    d = sub.add_parser("discover-sources")
    d.add_argument("--topic", required=True)
    d.add_argument("--query")
    d.set_defaults(func=cmd_discover_sources)
    v = sub.add_parser("verify-sources")
    v.add_argument("--list", action="store_true")
    v.add_argument("--approve", metavar="SOURCE_ID")
    v.add_argument("--reject", metavar="SOURCE_ID")
    v.add_argument("--license")
    v.add_argument("--reference")
    v.add_argument("--date")
    v.add_argument("--notes")
    v.add_argument("--reviewer")
    v.set_defaults(func=cmd_verify_sources)
    g = sub.add_parser("generate-script")
    g.add_argument("--topic", required=True)
    g.add_argument("--duration", type=int, choices=[15, 20, 30, 45, 60])
    g.set_defaults(func=cmd_generate_script)
    gv = sub.add_parser("generate-video")
    gv.add_argument("--video", required=True)
    gv.set_defaults(func=cmd_generate_video)
    q = sub.add_parser("qc")
    q.add_argument("--video", required=True)
    q.set_defaults(func=cmd_qc)
    rv = sub.add_parser("review")
    rv.add_argument("--video")
    rv.add_argument("--reviewer")
    act = rv.add_mutually_exclusive_group()
    act.add_argument("--approve", action="store_true")
    act.add_argument("--reject", action="store_true")
    act.add_argument("--edit-title")
    act.add_argument("--edit-description-file")
    act.add_argument("--edit-script", metavar="YAML_FILE")
    act.add_argument("--render-again", action="store_true")
    act.add_argument("--schedule", metavar="ISO_TIME")
    rv.add_argument("--allow-public", action="store_true", help="explicitly allow public release")
    rv.add_argument("--notes")
    rv.set_defaults(func=cmd_review)
    u = sub.add_parser("upload")
    u.add_argument("--video", required=True)
    u.add_argument("--privacy", choices=["private", "unlisted", "public"])
    u.add_argument("--live", action="store_true", help="actually upload (also requires DRY_RUN=false)")
    u.set_defaults(func=cmd_upload)
    a = sub.add_parser("analytics")
    a.add_argument("--collect", action="store_true")
    a.add_argument("--import-csv")
    a.add_argument("--record", metavar="VIDEO_ID")
    for f in ("views", "likes", "comments", "shares", "subscribers_gained"):
        a.add_argument(f"--{f.replace('_', '-')}", dest=f, type=int)
    a.add_argument("--avg-view-percentage", dest="avg_view_percentage", type=float)
    a.set_defaults(func=cmd_analytics)
    e = sub.add_parser("experiments")
    e.add_argument("action", choices=["create", "list", "assign", "analyze"])
    e.add_argument("--name")
    e.add_argument("--variable")
    e.add_argument("--variants")
    e.add_argument("--hypothesis")
    e.add_argument("--metric", default="views")
    e.add_argument("--experiment")
    e.add_argument("--video")
    e.add_argument("--variant")
    e.set_defaults(func=cmd_experiments)
    sub.add_parser("dashboard").set_defaults(func=cmd_dashboard)
    sub.add_parser("costs").set_defaults(func=cmd_costs)
    f = sub.add_parser("finance")
    f.add_argument("--hypothetical-rpm", type=float)
    f.add_argument("--assume-eligible", action="store_true")
    f.add_argument("--fixed-monthly", type=float, default=0.0)
    f.add_argument("--add-revenue", type=float)
    f.add_argument("--category", default="other")
    f.add_argument("--start")
    f.add_argument("--end")
    f.add_argument("--video")
    f.add_argument("--notes")
    f.set_defaults(func=cmd_finance)
    sub.add_parser("calendar").set_defaults(func=cmd_calendar)
    sub.add_parser("status").set_defaults(func=cmd_status)
    pl = sub.add_parser("pipeline")
    pl.add_argument("--topic")
    pl.add_argument("--auto-research", action="store_true")
    pl.add_argument("--resume", metavar="VIDEO_ID")
    pl.add_argument("--from-stage", choices=["research", "sourcing", "scripting", "editing", "qc"])
    pl.set_defaults(func=cmd_pipeline)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    from studio.errors import StudioError
    try:
        args.func(args)
    except StudioError as exc:
        if args.debug:
            raise
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
