"""Sound design with original audio only.

* music: a slow ambient pad synthesised here (our composition, CC0), quiet
  enough to sit under narration and ducked further by the mixer
* sfx: a soft filtered-noise "whoosh" for section changes

Both are registered as sources with self-generated rights records, so the QC
"no unauthorized music" check can verify them like any licensed track. Use
licensed library music instead by placing files (with rights sidecars) in
sources/music and setting brand.music_style: library.
"""
from __future__ import annotations

import wave
from pathlib import Path

import numpy as np

from studio.sources import discovery, ingest
from studio.sources.providers import SourceCandidate
from studio.sources.rights import LicenseInfo
from studio.textutil import today

SR = 48000
# A minor-ish progression (Am7 - Fmaj7 - Cmaj7 - G6), voiced low and wide
CHORDS = [[57, 60, 64, 67], [53, 57, 60, 64], [48, 55, 59, 64], [55, 59, 62, 64]]


def _hz(midi: int) -> float:
    return 440.0 * 2 ** ((midi - 69) / 12)


def _write(path: Path, stereo: np.ndarray) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = (np.clip(stereo, -1, 1) * 32767).astype("<i2")
    with wave.open(str(path), "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(data.tobytes())
    return path


def ambient_pad(path: Path, duration: float, bpm: float = 64.0, seed: int = 3) -> Path:
    rng = np.random.default_rng(seed)
    n = int(duration * SR)
    t = np.arange(n) / SR
    chord_len = 4 * 60.0 / bpm
    left = np.zeros(n, dtype=np.float64)
    right = np.zeros(n, dtype=np.float64)
    fade = int(1.2 * SR)
    for ci in range(int(np.ceil(duration / chord_len)) + 1):
        start = int(ci * chord_len * SR)
        end = min(n, int((ci + 1) * chord_len * SR) + fade)
        if start >= n:
            break
        seg_t = t[start:end] - t[start]
        env = np.minimum(1.0, seg_t / 1.4) * np.minimum(1.0, (seg_t[-1] - seg_t + 1e-9) / 1.2)
        for note in CHORDS[ci % len(CHORDS)]:
            f = _hz(note)
            for detune, pan in ((-0.12, 0.35), (0.12, 0.65)):
                ff = f * 2 ** (detune / 12)
                phase = rng.uniform(0, 2 * np.pi)
                tone = 0.7 * np.sin(2 * np.pi * ff * seg_t + phase) + 0.2 * np.sin(4 * np.pi * ff * seg_t + phase)
                left[start:end] += tone * env * (1 - pan)
                right[start:end] += tone * env * pan
    # gentle low-pass (Hann-window FIR, cutoff ~1.5 kHz) and slow tremolo for movement
    kernel = np.hanning(33)
    kernel /= kernel.sum()
    left = np.convolve(left, kernel, mode="same")
    right = np.convolve(right, kernel, mode="same")
    trem = 0.85 + 0.15 * np.sin(2 * np.pi * 0.07 * t)
    stereo = np.stack([left * trem, right * trem], axis=1)
    stereo /= np.abs(stereo).max() + 1e-9
    stereo *= 0.5
    edge = int(1.5 * SR)
    stereo[:edge] *= np.linspace(0, 1, edge)[:, None]
    stereo[-edge:] *= np.linspace(1, 0, edge)[:, None]
    return _write(path, stereo)


def whoosh(path: Path, length: float = 0.45, seed: int = 9) -> Path:
    rng = np.random.default_rng(seed)
    n = int(length * SR)
    noise = rng.standard_normal(n)
    # sweep a simple resonant band-pass by filtering with a moving one-pole pair
    out = np.zeros(n)
    lo = hi = 0.0
    for i in range(n):
        k = 0.02 + 0.25 * (i / n)
        lo += k * (noise[i] - lo)
        hi += 0.5 * (lo - hi)
        out[i] = lo - hi
    env = np.sin(np.pi * np.linspace(0, 1, n)) ** 2
    mono = out * env
    mono /= np.abs(mono).max() + 1e-9
    stereo = np.stack([mono * 0.4, mono * 0.4], axis=1)
    return _write(path, stereo)


def _register(ctx, path: Path, *, role: str, title: str, generator: str, params: dict) -> dict:
    brand = ctx.brand.get("channel_name", "this channel")
    lic = LicenseInfo(license_type="CC0-1.0", license_url="https://creativecommons.org/publicdomain/zero/1.0/",
                      commercial_use_allowed=True, modification_allowed=True, attribution_required=False,
                      audio_reuse_allowed=True, creator=f"{brand} (generated by ttengine.sound)",
                      permission_reference=f"self-generated: ttengine.sound.{generator}",
                      permission_date=today().isoformat(),
                      permission_notes="Original synthesised audio; no samples or third-party recordings.",
                      evidence_kind="manifest", evidence={"generator": generator, "params": params})
    cand = SourceCandidate(source_url=f"generated://{generator}/{path.stem}", platform="generated", title=title,
                           media_type="audio", license=lic, creator=lic.creator, description=title,
                           tags=[role, generator], local_path=str(path), role=role)
    sid, ok, reasons = discovery.record_candidate(ctx, cand, topic_id=None)
    if not ok:
        raise RuntimeError(f"generated audio failed the rights gate: {reasons}")
    return ingest.ingest(ctx, sid)


def music_bed(ctx, duration: float) -> dict | None:
    style = ctx.brand.get("music_style", "ambient_pad")
    if ctx.cfg.get("music.policy") == "none" or style == "none":
        return None
    if style == "library":
        rows = ctx.db.query("SELECT s.* FROM sources s JOIN licenses l ON l.source_id = s.source_id WHERE s.role = "
                            "'music' AND s.platform != 'generated' AND s.status = 'INGESTED' AND "
                            "l.verification_status = 'VERIFIED' ORDER BY s.date_found LIMIT 1")
        return rows[0] if rows else None
    length = round(duration + 2, 1)
    path = ctx.ws.home / "sources" / "generated" / f"ambient_pad_{int(length * 10)}.wav"
    if not path.exists():
        ambient_pad(path, length)
    return _register(ctx, path, role="music", title=f"Original ambient pad ({length}s)", generator="ambient_pad",
                     params={"duration": length, "bpm": 64, "chords": "Am7-Fmaj7-Cmaj7-G6"})


def transition_sfx(ctx) -> dict | None:
    if not ctx.cfg.get("sfx.enabled"):
        return None
    path = ctx.ws.home / "sources" / "generated" / "whoosh.wav"
    if not path.exists():
        whoosh(path)
    return _register(ctx, path, role="sfx", title="Original soft whoosh", generator="whoosh", params={"length": 0.45})
